# Generated by Django 4.2 on 2024-03-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=100)),
                ('jav1', models.CharField(max_length=50)),
                ('jav2', models.CharField(max_length=50)),
                ('jav3', models.CharField(max_length=50)),
                ('togri_jav', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Rus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=100)),
                ('jav1', models.CharField(max_length=50)),
                ('jav2', models.CharField(max_length=50)),
                ('jav3', models.CharField(max_length=50)),
                ('togri_jav', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
