# Generated by Django 4.2 on 2024-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=100)),
                ('jav1', models.CharField(max_length=50)),
                ('jav2', models.CharField(max_length=50)),
                ('jav3', models.CharField(max_length=50)),
                ('togri_jav', models.CharField(max_length=50)),
            ],
        ),
    ]
